---
- include_vars: locations.yml

- file: path={{www_root}} state=directory
  ignore_errors: yes

- replace: dest=/etc/php.ini regexp='^;cgi.fix_pathinfo=1$' replace='cgi.fix_pathinfo=0' backup=yes
  ignore_errors: yes

- template: src=nginx/default.conf.j2 dest=/etc/nginx/conf.d/default.conf

- replace: dest=/etc/php-fpm.d/www.conf regexp='^user = apache$' replace='user = nginx' backup=yes
- replace: dest=/etc/php-fpm.d/www.conf regexp='^group = apache$' replace='group = nginx' 
- replace: dest=/etc/nginx/nginx.conf regexp='^worker_process[ ]*1$' replace='worker_processes  4' 

- template: src=nginx/index.php.j2 dest={{www_root}}/index.php
